# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.Gym'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='year_Experience',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
