# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'gymnast'), (2, 'trainer'), (3, 'gym_manager')], null=True),
        ),
    ]
