# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymnast',
            name='chatroom',
            field=models.ManyToManyField(blank=True, to='gym.Chatroom'),
        ),
        migrations.AlterField(
            model_name='gymnast',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.Gym'),
        ),
    ]
