# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymnast',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gymnast',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
