# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_auto_20181107_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrate', to=settings.AUTH_USER_MODEL),
        ),
    ]
