# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_auto_20181108_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymnast',
            name='bmi',
            field=models.IntegerField(null=True),
        ),
    ]
