# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20181108_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='created',
            new_name='From',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='entry',
            name='To',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
