# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20181107_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('info', models.TextField(max_length=100)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrate', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='chatroom', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.AlterField(
            model_name='gymnast',
            name='chatroom',
            field=models.ManyToManyField(to='gym.Chatroom'),
        ),
        migrations.AlterField(
            model_name='post',
            name='chatroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='gym.Chatroom'),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
