# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20181104_0600'),
        ('gym', '0002_auto_20181103_2003'),
    ]

    operations = [
    ]
