# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_trainer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='facebook',
            field=models.URLField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='instagram',
            field=models.URLField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='twitter',
            field=models.URLField(blank=True, max_length=70, null=True),
        ),
    ]
