# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_merge_20181104_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.GymManager'),
        ),
    ]
