# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_auto_20181104_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Client'), (2, 'Trainer'), (3, 'Gym manager')], null=True),
        ),
    ]
