# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_auto_20181107_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
