# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_chatroom_users'),
        ('gym', '0006_auto_20181104_1913'),
    ]

    operations = [
    ]
