# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_chatroom_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['posted_on']},
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='time',
            new_name='posted_on',
        ),
    ]
