# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 04:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_auto_20181104_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
