# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_auto_20181107_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['posted_on']},
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='posted_on',
        ),
        migrations.AddField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
