# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_auto_20181105_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
