# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_auto_20181107_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='info',
            new_name='topic',
        ),
    ]
