# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 07:38
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_auto_20181105_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='address',
            field=django_google_maps.fields.AddressField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gym',
            name='location',
            field=django_google_maps.fields.GeoLocationField(max_length=100),
        ),
    ]
