# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_auto_20181107_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='address',
        ),
        migrations.AlterField(
            model_name='gym',
            name='location',
            field=models.TextField(),
        ),
    ]
