# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 09:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_auto_20181107_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
