# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_auto_20181107_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='location',
            new_name='geom',
        ),
    ]
